{% set conda_version = "25.1.1" %}
{% set conda_libmamba_solver_version = "25.3.0" %}
{% set libmambapy_version = "2.0.5" %}
{% set constructor_version = "3.11.3" %}
{% set menuinst_lower_bound = "2.2.0" %}
{% set python_version = "3.12.9" %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/{{ conda_version }}.tar.gz
    sha256: 896e8a9d137c2a03d92d75906df78c8d6ecaf44719ccddc2862a099e5fc498ed
  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 97dcb3857f5d65feb2b877a64bcb73a4fc4dbeee93085b848dfffa5985533714
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Restrict-search-paths.patch"
  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: b1b0bb88a8934508f837c892b4f9c3f08b34bf044b704b1fde44b148c236efbe  # [win]
    folder: constructor_src  # [win]

build:
  number: 1
  ignore_run_exports:
    - '*'
  script_env:
    - CONDA_STANDALONE_TEST_CHANNEL=defaults
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.9.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - conda
    - menuinst >={{ menuinst_lower_bound }}
    - pytest
    - ruamel.yaml
  source_files:
    - tests
  commands:
    - pytest -vv # [not s390x]
    - pytest -vv -k "not test_new_environment" # [s390x]
    - test ! -f {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
  description: A standalone conda executable built with PyInstaller.
  license: LicenseRef-CondaStandalone
  license_family: Other
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  doc_url: https://github.com/conda/conda-standalone
  dev_url: https://github.com/conda/conda-standalone

extra:
  recipe-maintainers:
    - jaimergp
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
