# {% set debug = os.environ.get('CONDA_BUILD_CONDA_STANDALONE_DEBUG', '') %}
# {% if CONDA_BUILD_CONDA_STANDALONE_DEBUG == 'yes' %}
#  {% set debug = 'yes' %}
# {% endif %}
# {% if debug != '' %}
#   {% set debug = "_dbg" %}
# {% endif %}

{% set debug = "" %}

package:
  name: conda-standalone
  version: {{ CONDA_VERSION }}

source:
  - path: ./
  - git_url: https://github.com/conda/conda
    git_tag: {{ CONDA_VERSION }}
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda..patch
      - conda_patches/0003-Remove-preload_openssl-it-is-so-so-wrong.patch
      # - conda_patches/0004-multiprocessing.set_start_method-fork-for-darwin-on-.patch
  - git_url: https://github.com/conda/constructor    # [win]
    git_tag: 3.0.2   # [win]
    folder: constructor   # [win]

build:
  number: 0

requirements:
  build:
    - git
  host:
    - python=3.8.5
    - pyinstaller
    - conda ={{ environ.get("CONDA_VERSION", 4) }}
    - conda-package-handling >=1.7.2
    - menuinst >=1.4.18  # [win]

test:
  commands:
    - "${PREFIX}/standalone_conda/conda.exe -V"  # [unix]
    - "${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm" # [unix]
    - "%PREFIX%\\standalone_conda\\conda.exe -V"  # [win]
    - "%PREFIX%\\standalone_conda\\conda.exe create -y -p env_test zlib tqdm"  # [win]


about:
  summary: Entry point and dependency collection for PyInstaller-based standalone conda
