{% set version = "22.11.0" %}
{% set constructor_version = "3.2.2" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: f280c1e68601adbfacb63d71d7319b0067f9e2543bb56b98d8093d22617ee42e
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda..patch
  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 57497a316a26631bb56c354a727980889015a1a79bf1a51131695ddbc51a0ca5  # [win]
    folder: constructor  # [win]

build:
  number: 0

requirements:
  build:
    - pyinstaller 5.6.2
    - python {{ python_version }}
    - conda {{ version }}
    - conda-package-handling >=1.6
    - menuinst >=1.4.18  # [win]
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  commands:
    - "${PREFIX}/standalone_conda/conda.exe -V"  # [unix]
    - "${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm" # [unix]
    - "%PREFIX%\\standalone_conda\\conda.exe -V"  # [win]
    - "%PREFIX%\\standalone_conda\\conda.exe create -y -p env_test zlib tqdm"  # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
