{% set version = "22.11.1" %}
{% set constructor_version = "3.3.1" %}
{% set menuinst_version = "1.4.19" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: f9256a7e71a9f35063b683f6c7823acf05c1f75468fc609954f1f5efae7c03ac
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda..patch
      - conda_patches/0005-menuinst-set-root-prefix.patch
  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: b000dde0ac8641c92f7342362173968505d4e85845be37655b5b9221cb65f3a8  # [win]
    folder: constructor  # [win]
  # This patch is still necessary because sys.prefix points to the TMP location
  # It cannot be patched in conda because the _conda.exe file that is executed
  # to create these menus does not appears to be conda-standalone
  - url: https://github.com/conda/menuinst/archive/refs/tags/{{ menuinst_version }}.tar.gz  # [win]
    sha256: f93ef4bc4e627868b7bba62ef8cb675e84d5bbe69a85a03a7559e1979f3924ec                # [win]
    folder: menuinst_src                                                                    # [win]
    patches:                                                                                # [win]
      - menuinst_patches/0003-root-prefix-to-prefix.patch                                   # [win]

build:
  number: 0

requirements:
  build:
    - pyinstaller 5.6.2
    - python {{ python_version }}
    - conda {{ version }}
    - conda-package-handling >=1.7.2
    - patch  # [not win]
    - m2-patch  # [win]
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  commands:
    - "${PREFIX}/standalone_conda/conda.exe -V"  # [unix]
    - "${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm" # [unix]
    - "%PREFIX%\\standalone_conda\\conda.exe -V"  # [win]
    - "%PREFIX%\\standalone_conda\\conda.exe create -y -p env_test zlib tqdm"  # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
