{% set version = "25.11.0" %}
{% set conda_version = version %}
{% set conda_libmamba_solver_version = "25.11.0" %}
{% set libmambapy_version = "2.3.2" %}
{% set constructor_lower_bound = "3.12.1" %}
{% set menuinst_lower_bound = "2.4.1" %}
{% set python_version = "3.13.10" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-standalone/archive/refs/tags/{{ version }}.tar.gz
    sha256: ef0453524062e76eaa30b41fb249a54c627761138ca738c0343a8cafd78d975b
    patches:
      - 0001-fix-path-prepend.patch
  - url: https://github.com/conda/conda/releases/download/{{ conda_version }}/conda-{{ conda_version }}.tar.gz
    sha256: 62aad5c046936b07e3ea44d6d908f2d94b427049420332def421e9c72ff3961e
    folder: conda_src
    patches:
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0003-Restrict-search-paths.patch"
      - "{{ SRC_DIR | replace('\\', '/') }}/src/conda_patches/0004-Fix-conda-run.patch"

build:
  number: 1
  string: "h{{ PKG_HASH }}_single_{{ PKG_BUILDNUM }}"  # [variant != 'onedir']
  string: "h{{ PKG_HASH }}_onedir_{{ PKG_BUILDNUM }}"  # [variant == 'onedir']
  detect_binary_files_with_prefix: False  # [variant == 'onedir']
  track_features:
    - conda-standalone_onedir  # [variant == 'onedir']
  ignore_run_exports:
    - '*'
  missing_dso_whitelist:          # [osx and variant == 'onedir']
    - "$RPATH/libswift*.dylib"    # [osx and variant == 'onedir']
  rpaths:                         # [linux and variant == 'onedir']
    - standalone_conda/_internal  # [linux and variant == 'onedir']
  overlinking_ignore_patterns:    # [win and variant == 'onedir']
    - '*'                         # [win and variant == 'onedir']
  script_env:
    - CONDA_STANDALONE_TEST_CHANNEL=defaults
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}
    - PYINSTALLER_BUILD_VARIANT={{ variant }}

requirements:
  build:
    - {{ stdlib('c') }}
    - libarchive >=3.8.2
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.12.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_lower_bound }}

test:
  requires:
    - conda
    - menuinst >={{ menuinst_lower_bound }}
    - pytest
    - ruamel.yaml
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - ./3rd-party-licenses.json
  license_family: Other
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
  description: A standalone conda executable built with PyInstaller.
  doc_url: https://github.com/conda/conda-standalone
  dev_url: https://github.com/conda/conda-standalone

extra:
  recipe-maintainers:
    - jaimergp
    - marcoesters
    - msarahan
    - nehaljwani
