@ECHO ON 
SET "PYINSTALLER_CONDARC_DIR=%RECIPE_DIR%"
IF NOT EXIST "%PYINSTALLER_CONDARC_DIR%" (
    ECHO "Could not find directory %PYINSTALLER_CONDARC_DIR%"
    EXIT /B 1
)
echo. > "%PREFIX%\.nonadmin"
IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
